model:
    name: 'MLPRULPredictor'
    in_channels: 1
    channels: 32
    input_height: 1
    input_width: 1000
    epochs: 5000
    batch_size: 128
    evaluate_freq: 100
train_test_split:
    name: 'MIX100TrainTestSplitter'
    cell_data_path:
        - 'data/preprocessed/CALCE'
        - 'data/preprocessed/RWTH'
        - 'data/preprocessed/UL_PUR'
        - 'data/preprocessed/HNEI'
        - 'data/preprocessed/MATR'
        - 'data/preprocessed/HUST'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 9
    max_cycle_index: 99
    cycles_to_keep: 99
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
