model:
    name: 'LinearRegressionRULPredictor'
train_test_split:
    name: 'CRUSHTrainTestSplitter'
    cell_data_path:
        - 'data/preprocessed/CALCE'
        - 'data/preprocessed/RWTH'
        - 'data/preprocessed/UL_PUR'
        - 'data/preprocessed/SNL'
        - 'data/preprocessed/HNEI'
feature:
    name: 'FullModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 19
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.9
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
