model:
    name: 'PCRRULPredictor'
    n_components: 12
train_test_split:
    name: 'MIX100TrainTestSplitter'
    cell_data_path:
        - 'data/preprocessed/CALCE'
        - 'data/preprocessed/RWTH'
        - 'data/preprocessed/UL_PUR'
        - 'data/preprocessed/HNEI'
        - 'data/preprocessed/MATR'
        - 'data/preprocessed/HUST'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 8
    max_cycle_index: 98
    cycles_to_keep: 98
    use_precalculated_qdlin: True
label:
    name: 'RULLabelAnnotator'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
