model:
    name: 'LinearRegressionRULPredictor'
train_test_split:
    name: 'CRUHTrainTestSplitter'
    cell_data_path:
        - 'data/preprocessed/CALCE'
        - 'data/preprocessed/RWTH'
        - 'data/preprocessed/UL_PUR'
        - 'data/preprocessed/HNEI'
feature:
    name: 'VarianceModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 9
        - 99
label:
    name: 'RULLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
