model:
    name: 'RandomForestRULPredictor'
train_test_split:
    name: 'CRUSHTrainTestSplitter'
    cell_data_path:
        - 'data/preprocessed/CALCE'
        - 'data/preprocessed/RWTH'
        - 'data/preprocessed/UL_PUR'
        - 'data/preprocessed/SNL'
        - 'data/preprocessed/HNEI'
feature:
    name: 'VoltageCapacityMatrixFeatureExtractor'
    diff_base: 2
    max_cycle_index: 19
    cycles_to_keep: 19
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.9
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'